#!/usr/bin/env python3
"""JSON benchmarks and conformance (docs/design/json.md, section 12).

Builds bench/json/json_bench.goose and conformance.goose with the Goose
compiler and a C toolchain, and the yyjson baseline from
third_party/yyjson.c with the same toolchain; runs each on the corpus in
data/, best of --reps runs; checks JSONTestSuite (third_party/JSONTestSuite)
through the document parser and a fully walked cursor; and writes
results.md and results.json beside this file.

  python bench/json/json_bench.py                 # everything
  python bench/json/json_bench.py --reps 100      # more runs per measurement
  python bench/json/json_bench.py --report-only   # re-render from results.json

Each measurement is the best of its runs: the machine's noise only ever
adds time. The yyjson columns run beside the Goose ones in the same
invocation, so their ratio means more than either number alone on a busy
machine.
"""

import argparse
import json
import os
import platform
import re
import sys
from datetime import datetime
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent.parent / "scripts"))
import toolchain as tc

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent.parent
GEN = ROOT / "bench" / "gen" / "json"
DATA = HERE / "data"
SUITE = HERE / "third_party" / "JSONTestSuite"

# The corpus, each with a lookup near its end: (file, key1, key2).
CORPUS = [
    ("twitter.json", "search_metadata", "count"),
    ("citm_catalog.json", "venueNames", "PLEYEL_PLEYEL"),
    ("canada.json", "type", "x"),
]


def build_goose(goose, cc, name):
    exe = GEN / f"{name}{tc.EXE_SUFFIX}"
    cfile = GEN / f"{name}.c"
    code, out, err = tc.run_capture([goose, "-O2", "--standalone", "-o", cfile, HERE / f"{name}.goose"])
    tc.write_text(GEN / f"{name}.goose.log", out + err)
    if code != 0:
        sys.exit(f"goose failed on {name}.goose, see {GEN / (name + '.goose.log')}")
    ok, msg = cc.compile(cfile, exe, opt=2, log=GEN / f"{name}.cc.log")
    if not ok:
        sys.exit(f"{cc.name} failed on {name}, see {GEN / (name + '.cc.log')}")
    return exe


def build_yyjson(cc):
    exe = GEN / f"yyjson_bench{tc.EXE_SUFFIX}"
    ok, msg = cc.compile([HERE / "baselines" / "yyjson_bench.c", HERE / "third_party" / "yyjson.c"],
                         exe, opt=2, warn="none", log=GEN / "yyjson.cc.log")
    return exe if ok else None


def pairs(line):
    return {k: int(float(v)) for k, v in (f.split("=", 1) for f in line.split())}


def run(exe, *args):
    code, out, err = tc.run_capture([exe, *map(str, args)])
    if code != 0:
        sys.exit(f"{exe} failed: {err or out}")
    return out.strip().splitlines()[-1]


def conformance(exe):
    files = sorted(SUITE.glob("*.json"))
    code, out, err = tc.run_capture([exe, *map(str, files)])
    if code != 0:
        sys.exit(f"conformance failed: {err or out}")
    rows = {}
    for line in out.splitlines():
        name, doc, cur = line.rsplit(" ", 2)
        rows[Path(name).name] = (doc, cur)
    res = {"y": [0, 0], "n": [0, 0], "i": {}, "wrong": []}
    for name, (doc, cur) in sorted(rows.items()):
        kind = name[:1]
        if kind == "y":
            res["y"][0] += doc == "accept"
            res["y"][1] += 1
            if doc != "accept" or cur != "accept":
                res["wrong"].append(f"{name}: document {doc}, cursor {cur}")
        elif kind == "n":
            res["n"][0] += doc == "reject"
            res["n"][1] += 1
            if doc != "reject" or cur != "reject":
                res["wrong"].append(f"{name}: document {doc}, cursor {cur}")
        else:
            res["i"][name] = doc if doc == cur else f"{doc} (cursor {cur})"
    return res


def ratio(a, b):
    return f"{a / b:.0%}" if a and b else "–"


def render(r):
    lines = [
        "# JSON benchmarks",
        "",
        f"Measured {r['date']} on {r['machine']}, {r['cc']}; load average "
        f"{r['load']:.1f} when the run started. Best of {r['reps']} runs each. "
        "Generated by `bench/json/json_bench.py`; the design is "
        "`docs/design/json.md`.",
        "",
        "## Throughput (MB/s; write is per byte of output)",
        "",
        "| File | Size | Parse | yyjson | Ratio | Parse + walk | yyjson | Ratio | Write | yyjson | Ratio |",
        "|---|---|---|---|---|---|---|---|---|---|---|",
    ]
    for f in r["files"]:
        g, y = f["goose"], f.get("yyjson") or {}
        lines.append(
            f"| {f['file']} | {g['bytes'] / 1e6:.2f} MB | {g['parse']} | {y.get('parse', '–')} | "
            f"{ratio(g['parse'], y.get('parse'))} | {g['walk']} | {y.get('walk', '–')} | "
            f"{ratio(g['walk'], y.get('walk'))} | {g['write']} | {y.get('write', '–')} | "
            f"{ratio(g['write'], y.get('write'))} |")
    lines += [
        "",
        "## The cursor (MB/s)",
        "",
        "`index` is stage 1 alone. `find` is a cursor, then one lookup near the "
        "end of the text; `find (document)` is a whole parse, then the same lookup.",
        "",
        "| File | Lookup | Index | Find | Find (document) |",
        "|---|---|---|---|---|",
    ]
    for f in r["files"]:
        g = f["goose"]
        lines.append(f"| {f['file']} | `{f['key1']}.{f['key2']}` | {g['index']} | {g['find']} | {g['find_doc']} |")
    lines += [
        "",
        "## Doubles (ns each)",
        "",
        "| File | Doubles | Write | Read |",
        "|---|---|---|---|",
    ]
    for f in r["files"]:
        g = f["goose"]
        if g["doubles"] >= 1000:
            lines.append(f"| {f['file']} | {g['doubles']} | {g['fwrite_ps'] / 1000:.1f} | {g['fread_ps'] / 1000:.1f} |")
    c = r["conformance"]
    lines += [
        "",
        "## JSONTestSuite",
        "",
        f"* `y_` (must accept): {c['y'][0]}/{c['y'][1]} accepted.",
        f"* `n_` (must reject): {c['n'][0]}/{c['n'][1]} rejected.",
        "* Document and fully walked cursor disagree with the suite on: "
        + (", ".join(c["wrong"]) if c["wrong"] else "nothing") + ".",
        "",
        "`i_` (either is allowed):",
        "",
        "| File | Result |",
        "|---|---|",
    ]
    for name, v in c["i"].items():
        lines.append(f"| {name} | {v} |")
    lines.append("")
    return "\n".join(lines)


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--exe", help="the goose compiler (default: found as the tests find it)")
    ap.add_argument("--cc", help="C toolchain name (default: clang if present)")
    ap.add_argument("--reps", type=int, default=50, help="runs per measurement (default 50)")
    ap.add_argument("--report-only", action="store_true")
    args = ap.parse_args()
    tc.setup_console()
    rpath = HERE / "results.json"
    if args.report_only:
        r = json.loads(rpath.read_text())
        tc.write_text(HERE / "results.md", render(r))
        print(f"wrote {HERE / 'results.md'}")
        return 0

    goose = tc.find_goose(args.exe)
    ccs = tc.find_ccs()
    if not ccs:
        sys.exit("no C toolchain found")
    cc = ccs[args.cc or ("clang" if "clang" in ccs else next(iter(ccs)))]
    GEN.mkdir(parents=True, exist_ok=True)
    print(f"building with {cc.desc}...", flush=True)
    bench = build_goose(goose, cc, "json_bench")
    conf = build_goose(goose, cc, "conformance")
    yy = build_yyjson(cc)

    load = os.getloadavg()[0] if hasattr(os, "getloadavg") else 0.0
    files = []
    for name, k1, k2 in CORPUS:
        path = DATA / name
        print(f"{name}...", flush=True)
        g = pairs(run(bench, path, args.reps, k1, k2))
        y = pairs(run(yy, path, args.reps)) if yy else None
        files.append({"file": name, "key1": k1, "key2": k2, "goose": g, "yyjson": y})
    print("JSONTestSuite...", flush=True)
    r = {
        "date": datetime.now().strftime("%Y-%m-%d"),
        "machine": f"{platform.system()} {platform.machine()}",
        "cc": cc.desc,
        "load": load,
        "reps": args.reps,
        "files": files,
        "conformance": conformance(conf),
    }
    tc.write_text(rpath, json.dumps(r, indent=1) + "\n")
    tc.write_text(HERE / "results.md", render(r))
    print(f"wrote {HERE / 'results.md'}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
