#!/usr/bin/env python3
"""Writes stdlib/json/tables.goose: the constant tables of the json
module's number conversions. Run it again only to change a table.

* POW10_HI/LO: for e in [-292, 324], 10^e scaled to [2^127, 2^128) and
  rounded up, for writing doubles (Schubfach as in drachennest's
  schubfach_64: index e + 292 holds 10^e).
* POW2, POW10_F64: the exact powers of two and ten the conversions
  scale by.
* UTF8_DFA: UTF-8 validation, one table row per byte.
* POW5_HI/LO: for q in [-342, 308], 5^q scaled to [2^127, 2^128), as
  fast_float's table (truncated above 0, floor + 1 below), for reading
  them (Eisel-Lemire: index q + 342).
"""
from pathlib import Path

OUT = Path(__file__).resolve().parent.parent / "stdlib" / "json" / "tables.goose"


def pow10_table():
    rows = []
    for e in range(-292, 325):
        if e >= 0:
            num, den = 10 ** e, 1
        else:
            num, den = 1, 10 ** -e
        # The binary exponent b with 2^127 <= num/den * 2^b < 2^128.
        b = 127 - (num.bit_length() - den.bit_length())
        while True:
            n, d = (num << b, den) if b >= 0 else (num, den << -b)
            if n >= d << 128:
                b -= 1
            elif n < d << 127:
                b += 1
            else:
                break
        g = -(-n // d)  # round up
        assert (1 << 127) <= g < (1 << 128)
        rows.append(g)
    return rows


def pow5_table():
    rows = []
    for q in range(-342, 0):
        power5 = 5 ** -q
        z = 0
        while (1 << z) < power5:
            z += 1
        if q >= -27:
            b = z + 127
            c = 2 ** b // power5 + 1
        else:
            b = 2 * z + 2 * 64
            c = 2 ** b // power5 + 1
            while c >= (1 << 128):
                c //= 2
        rows.append(c)
    for q in range(0, 309):
        power5 = 5 ** q
        while power5 < (1 << 127):
            power5 *= 2
        while power5 >= (1 << 128):
            power5 //= 2
        rows.append(power5)
    return rows


def u64_array(name, values, per=4):
    lines = [f"const {name}: u64[{len(values)}] = ["]
    for i in range(0, len(values), per):
        lines.append("    " + " ".join(f"0x{v:016x}," for v in values[i:i + per]))
    lines.append("];")
    return "\n".join(lines)


def f64_array(name, values, per=4):
    lines = [f"const {name}: f64[{len(values)}] = ["]
    for i in range(0, len(values), per):
        lines.append("    " + " ".join(f"{float(v)!r}," for v in values[i:i + per]))
    lines.append("];")
    return "\n".join(lines)


def utf8_dfa():
    """A shift DFA: next state = (row[byte] >> state) & 63, states at
    multiples of 6 bits, 0 accepting, ERR a sink."""
    ACC, ERR, T1, T2, T3, E0, ED, F0, F4 = (6 * k for k in range(9))
    def step(state, b):
        cont = 0x80 <= b <= 0xbf
        if state == ACC:
            if b < 0x80: return ACC
            if b < 0xc2: return ERR
            if b < 0xe0: return T1
            if b == 0xe0: return E0
            if b == 0xed: return ED
            if b < 0xf0: return T2
            if b == 0xf0: return F0
            if b < 0xf4: return T3
            if b == 0xf4: return F4
            return ERR
        if state == T1: return ACC if cont else ERR
        if state == T2: return T1 if cont else ERR
        if state == T3: return T2 if cont else ERR
        if state == E0: return T1 if 0xa0 <= b <= 0xbf else ERR
        if state == ED: return T1 if 0x80 <= b <= 0x9f else ERR
        if state == F0: return T2 if 0x90 <= b <= 0xbf else ERR
        if state == F4: return T2 if 0x80 <= b <= 0x8f else ERR
        return ERR
    rows = []
    for b in range(256):
        row = 0
        for st in (ACC, ERR, T1, T2, T3, E0, ED, F0, F4):
            row |= step(st, b) << st
        rows.append(row)
    return rows


def main():
    p10 = pow10_table()
    p5 = pow5_table()
    mask = (1 << 64) - 1
    parts = [
        "// Generated by scripts/json_tables.py; do not edit.",
        "//",
        "// The 128-bit significands the number conversions multiply by.",
        "",
        "namespace json;",
        "",
        "// 10^e for e in [-292, 324], in [2^127, 2^128), rounded up: index e + 292.",
        u64_array("POW10_HI", [g >> 64 for g in p10]),
        u64_array("POW10_LO", [g & mask for g in p10]),
        "",
        "// 5^q for q in [-342, 308], in [2^127, 2^128): index q + 342.",
        u64_array("POW5_HI", [c >> 64 for c in p5]),
        u64_array("POW5_LO", [c & mask for c in p5]),
        "",
        "// 2^k for k in [-64, 63], exact: index k + 64.",
        f64_array("POW2", [2.0 ** k for k in range(-64, 64)]),
        "",
        "// 10^k for k in [0, 22]: the powers of ten a double holds exactly.",
        f64_array("POW10_F64", [10.0 ** k for k in range(23)]),
        "",
        "// UTF-8 validation as a shift DFA: state = (UTF8_DFA[byte] >> state) & 63,",
        "// 0 accepting (RFC 3629: no overlong forms, surrogates or values past U+10FFFF).",
        u64_array("UTF8_DFA", utf8_dfa()),
        "",
    ]
    OUT.write_text("\n".join(parts))
    print(f"wrote {OUT}")


if __name__ == "__main__":
    main()
