"""Writes the overloads of stdlib/sqlite.goose that take a statement's
parameters as arguments: exec, query, each, one and the scalar_* functions,
for 0 to MAX_ARGS parameters each. Goose has no variadic functions, so each
parameter count is an overload; they differ only in their bind() calls, so
they are generated rather than written out by hand, between the markers
`// --- generated by scripts/sqlite_arity.py: begin ---` and `end ---`.

Run it after changing the template below: python scripts/sqlite_arity.py
The test suite checks the file is up to date: --check exits 1 if not.
"""

import sys
from pathlib import Path

MAX_ARGS = 16
FILE = Path(__file__).resolve().parent.parent / "stdlib" / "sqlite.goose"
BEGIN = "// --- generated by scripts/sqlite_arity.py: begin ---\n"
END = "// --- generated by scripts/sqlite_arity.py: end ---\n"


def overloads(n):
    tys = [f"A{i}" for i in range(1, n + 1)]
    params = "".join(f", a{i}: A{i}" for i in range(1, n + 1))
    binds = "".join(f"    bind(s, {i}, a{i});\n" for i in range(1, n + 1))

    def generics(*extra):
        names = tys + list(extra)
        return f"<{', '.join(names)}>" if names else ""

    head = f"(db: Db, sql: const u8[:]{params})"
    prep = f"    let s = statement_for(db, sql, {n});\n"
    out = []
    out.append(f"fn exec{generics()}{head} -> bool {{\n{prep}"
               f"    if s.h == 0 {{ return false; }}\n{binds}    return run(s);\n}}\n")
    out.append(f"fn query{generics('F')}{head} {{\n{prep}"
               + (f"    if s.h != 0 {{\n{binds.replace('    bind', '        bind')}    }}\n" if n else "")
               + "    return collect(s, F);\n}\n")
    out.append(f"fn each{generics('F')}{head} -> bool {{\n{prep}"
               f"    if s.h == 0 {{ return false; }}\n{binds}    return each_row(s, F);\n}}\n")
    out.append(f"fn one{generics('F')}{head} -> bool, bool {{\n{prep}"
               f"    if s.h == 0 {{ return false, false; }}\n{binds}    return first_row(s, F);\n}}\n")
    for name, typ, read, zero in (("scalar_int", "i64", "int", "0"),
                                  ("scalar_real", "f64", "real", "0.0")):
        out.append(f"fn {name}{generics()}{head} -> {typ}, bool {{\n{prep}"
                   f"    if s.h == 0 {{ return {zero}, false; }}\n{binds}"
                   f"    var v: {typ} = {zero};\n"
                   f"    let found, ok = first_row(s) {{ r => v = {read}(r, 0); }};\n"
                   f"    return v, found && ok;\n}}\n")
    out.append(f"fn scalar_text{generics()}{head} -> u8[>..], bool {{\n"
               f"    var v: u8[>..] = [];\n{prep}"
               f"    if s.h == 0 {{ return v, false; }}\n{binds}"
               f"    let found, ok = first_row(s) {{ r => text_into(r, 0, v); }};\n"
               f"    return v, found && ok;\n}}\n")
    return out


def generated():
    parts = ["// exec(db, sql, args...) -> bool: runs a statement, ignoring any rows.\n"
             "// query(db, sql, args...) { r => T } -> T[>..], bool: every row, built by the block.\n"
             "// each(db, sql, args...) { r => ... } -> bool: each row to the block.\n"
             "// one(db, sql, args...) { r => ... } -> bool, bool: the first row to the block;\n"
             "//     whether there was one, and whether the statement ran.\n"
             "// scalar_int / scalar_real / scalar_text(db, sql, args...) -> v, bool: the first\n"
             "//     column of the first row; false for no row or a failure.\n"]
    for n in range(MAX_ARGS + 1):
        parts.append(f"\n// {n} parameter{'' if n == 1 else 's'}\n")
        parts.append("\n".join(overloads(n)))
    return "".join(parts)


def main():
    text = FILE.read_text(encoding="utf-8")
    start = text.index(BEGIN) + len(BEGIN)
    end = text.index(END)
    fresh = text[:start] + generated() + text[end:]
    if "--check" in sys.argv:
        if fresh != text:
            print(f"{FILE.name} is out of date: run python scripts/sqlite_arity.py")
            sys.exit(1)
        return
    FILE.write_text(fresh, encoding="utf-8", newline="\n")


if __name__ == "__main__":
    main()
